config/routes.rb
Rails.application.routes.draw do
  resources :setlist_songs do
    post :sort, on: :collection
  end

  resources :songs do
    post :sort, on: :collection
  end

  resources :setlists

  resources :books do
    post :sort, on: :collection
  end

  root to: "books#index"

end

app/models/setlist.rb
class Setlist < ActiveRecord::Base
  has_many :setlist_songs, -> { order(:position) }
  has_many :songs, :through => :setlist_songs
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
  before_action :set_setlist, only: [:show, :edit, :update, :destroy]

  # GET /setlists
  # GET /setlists.json
  def index
    @setlists = Setlist.all
  end

  # GET /setlists/1
  # GET /setlists/1.json
  def show
    @set_songs = @setlist.setlist_songs.order('setlist_songs.position ASC')
  end

  # GET /setlists/new
  def new
    @setlist = Setlist.new
  end

  # GET /setlists/1/edit
  def edit
  end

  # POST /setlists
  # POST /setlists.json
  def create
    @setlist = Setlist.new(setlist_params)

    respond_to do |format|
      if @setlist.save
        format.html { redirect_to @setlist, notice: 'Setlist was successfully created.' }
        format.json { render :show, status: :created, location: @setlist }
      else
        format.html { render :new }
        format.json { render json: @setlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setlists/1
  # PATCH/PUT /setlists/1.json
  def update
    respond_to do |format|
      if @setlist.update(setlist_params)
        format.html { redirect_to @setlist, notice: 'Setlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @setlist }
      else
        format.html { render :edit }
        format.json { render json: @setlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setlists/1
  # DELETE /setlists/1.json
  def destroy
    @setlist.destroy
    respond_to do |format|
      format.html { redirect_to setlists_url, notice: 'Setlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setlist
      @setlist = Setlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setlist_params
      params[:setlist]
    end
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/views/setlists/_form.html.erb
<%= form_for(@setlist) do |f| %>
  <% if @setlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setlist.errors.count, "error") %> prohibited this setlist from being saved:</h2>

      <ul>
      <% @setlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setlists/edit.html.erb
<h1>Editing setlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @setlist %> |
<%= link_to 'Back', setlists_path %>

app/views/setlists/index.html.erb
<h1>Listing setlists</h1>

<% @setlists.each do |setlist| %>
  <h2><%= link_to setlist.name, setlist %></h2>
<% end %>
<br>

<%= link_to 'New Setlist', new_setlist_path %>

app/views/setlists/new.html.erb
<h1>New setlist</h1>

<%= render 'form' %>

<%= link_to 'Back', setlists_path %>

app/views/setlists/show.html.erb
<h1><%=@setlist.name%>'s Songs:</h1>

<ul id="setlist_songs"> <% @set_songs.each do |setlist_song| %>
  <li id="setlist_song_<%= setlist_song.id %>"><span class="handle">[drag]</span><%= setlist_song.song.name %>, (Position: <%=setlist_song.position%>)</li>
<% end %></ul>

<%= link_to 'Edit', edit_setlist_path(@setlist) %> |
<%= link_to 'Back', setlists_path %>


<script>
  $(document).ready(function(){
    $('#setlist_songs').sortable({
      axis: 'y',
      dropOnEmpty: false,
      handle: '.handle',
      cursor: 'crosshair',
      items: 'li',
      opacity: 0.4,
      scroll: true,
      update: function(){
        $.ajax({
          type: 'post',
          data: $('#setlist_songs').sortable('serialize'),
          dataType: 'script',
          complete: function(request){
            $('#setlist_songs').effect('highlight');
          },
        url: '/setlist_songs/sort'})
      }
    });
  });
</script>