config/routes.rb
Rails.application.routes.draw do
  resources :setlist_songs do
    post :sort, on: :collection
  end

  resources :songs do
    post :sort, on: :collection
  end

  resources :setlists

  resources :books do
    post :sort, on: :collection
  end

  root to: "books#index"

end

app/models/setlist_song.rb
class SetlistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :setlist

  acts_as_list :scope => :setlist
end

app/controllers/setlist_songs_controller.rb
class SetlistSongsController < ApplicationController
  before_action :set_setlist_song, only: [:show, :edit, :update, :destroy]

  # GET /setlist_songs
  # GET /setlist_songs.json
  def index
    @setlist_songs = SetlistSong.where(setlist_id: 2).order('setlist_songs.position ASC')
  end

  def sort
    @setlist_songs = SetlistSong.all
    @setlist_songs.each do |setlist_song|
      song_index = params['setlist_song'].index(setlist_song.id.to_s)
      unless song_index.nil?
        setlist_song.position = song_index + 1
        setlist_song.save
      end
    end

    render :nothing => true

  end


  # GET /setlist_songs/1
  # GET /setlist_songs/1.json
  def show
  end

  # GET /setlist_songs/new
  def new
    @setlist_song = SetlistSong.new
  end

  # GET /setlist_songs/1/edit
  def edit
  end

  # POST /setlist_songs
  # POST /setlist_songs.json
  def create
    @setlist_song = SetlistSong.new(setlist_song_params)

    respond_to do |format|
      if @setlist_song.save
        format.html { redirect_to @setlist_song, notice: 'Setlist song was successfully created.' }
        format.json { render :show, status: :created, location: @setlist_song }
      else
        format.html { render :new }
        format.json { render json: @setlist_song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setlist_songs/1
  # PATCH/PUT /setlist_songs/1.json
  def update
    respond_to do |format|
      if @setlist_song.update(setlist_song_params)
        format.html { redirect_to @setlist_song, notice: 'Setlist song was successfully updated.' }
        format.json { render :show, status: :ok, location: @setlist_song }
      else
        format.html { render :edit }
        format.json { render json: @setlist_song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setlist_songs/1
  # DELETE /setlist_songs/1.json
  def destroy
    @setlist_song.destroy
    respond_to do |format|
      format.html { redirect_to setlist_songs_url, notice: 'Setlist song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setlist_song
      @setlist_song = SetlistSong.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setlist_song_params
      params[:setlist_song]
    end
end

app/helpers/setlist_songs_helper.rb
module SetlistSongsHelper
end

app/views/setlist_songs/_form.html.erb
<%= form_for(@setlist_song) do |f| %>
  <% if @setlist_song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setlist_song.errors.count, "error") %> prohibited this setlist_song from being saved:</h2>

      <ul>
      <% @setlist_song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setlist_songs/edit.html.erb
<h1>Editing setlist_song</h1>

<%= render 'form' %>

<%= link_to 'Show', @setlist_song %> |
<%= link_to 'Back', setlist_songs_path %>

app/views/setlist_songs/index.html.erb
<h1>Listing setlist_songs</h1>

<ul id="setlist_songs"> <% @setlist_songs.each do |setlist_song| %>
  <li id="setlist_song_<%= setlist_song.id %>"><span class="handle">[drag]</span><b>ID: </b><%= setlist_song.id %>, <b>Position: </b> <%=setlist_song.position%>, <b>Song: </b><%= setlist_song.song.name %>, <b>Setlist: </b><%= setlist_song.setlist.name %></li>
<% end %></ul>

<br>



<script>
  $(document).ready(function(){
    $('#setlist_songs').sortable({
      axis: 'y',
      dropOnEmpty: false,
      handle: '.handle',
      cursor: 'crosshair',
      items: 'li',
      opacity: 0.4,
      scroll: true,
      update: function(){
        $.ajax({
          type: 'post',
          data: $('#setlist_songs').sortable('serialize'),
          dataType: 'script',
          complete: function(request){
            $('#setlist_songs').effect('highlight');
          },
        url: '/setlist_songs/sort'})
      }
    });
  });
</script>

app/views/setlist_songs/new.html.erb
<h1>New setlist_song</h1>

<%= render 'form' %>

<%= link_to 'Back', setlist_songs_path %>

app/views/setlist_songs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_setlist_song_path(@setlist_song) %> |
<%= link_to 'Back', setlist_songs_path %>